$_version = "Version";
$_menu3_title1 = 'Geographic shortcuts';
$_menu3_title2 = 'Wind';
$_menu3_title3 = 'Precipitation';
$_menu3_title4 = 'Cloud';
$_menu3_title5 = 'Temperatures';
$_menu3_title6 = 'Aerology';
$_menu_preferences = "Settings"
$_layer = "parameter";
$_previsions = "Forecasts";
$_observations = "Observations"

$_layer_uv_10m = 'Wind 10m';
$_layer_uv_alt = 'Upper wind';
$_layer_rafale = 'Wind gust 10m (kt)';
$_layer_opacityLabel = 'Opacity';
$_layer_elevationLabel = 'Level';

$_layer_t = 'Temperature';
$_layer_td = 'Td 2m';
$_layer_rrtt = 'Precipitations totales';Températures
$_coupe_terrain = "Time-section plot";
$_coupe_trajet = "Cross-section route";
$_parametres = "Parameters";
$_choix_language = "Choose language";
$_francais = "French";
$_anglais = "English";
$_layer_radar_fr = "Radar imagery";
$_layer_foudre_fr = "Lightning";
$_imagerie = "Observed imagery";

$_Dimanche = "Sunday";
$_Lundi = "Monday";
$_Mardi = "Tuesday";
$_Mercredi = "Wednesday";
$_Jeudi = "Thursday";
$_Vendredi = "Friday";
$_Samedi = "Saturday";

$_Dimanche_bref = "S";
$_Lundi_bref = "M";
$_Mardi_bref = "T";
$_Mercredi_bref = "W";
$_Jeudi_bref = "T";
$_Vendredi_bref = "F";
$_Samedi_bref = "S";

$_Dimanche_short = "Sun";
$_Lundi_short = "Mon";
$_Mardi_short = "Tue";
$_Mercredi_short = "Wed";
$_Jeudi_short = "Thu";
$_Vendredi_short = "Fri";
$_Samedi_short = "Sat";

$_Janvier = "January";
$_Fevrier = "February";
$_Mars = "March";
$_Avril = "April";
$_Mai = "May"
$_Juin = "June";
$_Juillet = "July";
$_Aout = "August";
$_Septembre = "September";
$_Octobre = "October";
$_Novembre = "November";
$_Decembre = "December";

$_Janvier_short = "Janu";
$_Fevrier_short = "Febr";
$_Mars_short = "Marc";
$_Avril_short = "Apri";
$_Mai_short = "May"
$_Juin_short = "June";
$_Juillet_short = "July";
$_Aout_short = "Augu";
$_Septembre_short = "Septe";
$_Octobre_short = "Octo";
$_Novembre_short = "Nove";
$_Decembre_short = "Dece";
$_fr = "France ";
$_re = "Reunion Island";
$_my = "Mayotte";
$_ga = "Guadeloupe";
$_ma = "Martinique";
$_gy = "Guyana ";
$_po = "French Polynesia";
$_nc = "new Caledonia";
$_sp = "Saint pierre and miquelon";
$_choix_geo = "Choose location";
$_choix_repere = "Choose yours markers";
$_repere_dep = "Departments";
$_repere_front = "Boundaries";
$_repere_grat = 'Grids';
$_repere_aero = 'Airports';
$_label_choix_run_arome = "Choice of model Arome date";
$_label_choix_run_arpege = "Choice of model Arpege date";
$_analyse_generale = "Surface analysis";
$_t_layer_arpege = "Temperature";
$_z_layer_arpege = "Geopotential height";
$_no_new_modele = "No new model available."
$_nouveau_modele_arome_dispo = "New Arome model available.";
$_nouveau_modele_arpege_dispo = "New Arpege model available.";
$_depart = "Departure";
$_etape = "Stopover";
$_arrivee = "Arrival";
$_coupe_trajet_vide = "To start, select points on the map. Or a route already recorded.";
$_coupe_terrain_vide = "To start, select a point on the map. Or a time-section plot already recorded.";
$_valider_le_trajet = "Validate the route.";
$_valider_le_terrain = "Validate the time-section plot.";
$_valider = "Validate";
$_annuler = "Cancel";
$_aucun_trajet = "No recorded route.";
$_aucun_terrain = "No time-section plot.";
$_hu = "Humidity";
$_rflctvt = "Reflectivity";
$_vv2 = "Vertical Speed. (m.s-1)";
$_iso_m10 = "Iso -10°";
$_iso_0 = "Iso 0°";
$_iso_p5 = "Iso +5°";
$_theta = "Theta";
$_tke = "TKE";
$_hcl = "Boundary limit height (m)";
$_uv_alt = "Upper wind";
$_t = "Temperature";
$_choix_parametre_trajet = "Choose your settings";
$_choix_parametre_terrain = "Choose your settings";
$_choix_trajet = "Choose your route";
$_choix_terrain = "Choose your time-section plot";
$_donne_nom_trajet = "Give a name to this route";
$_donne_nom_terrain = "Give a name to this time-section plot";
$_liste_trajets_enregistres = "List of recorded route";
$_liste_terrains_enregistres = "List of time-section plot";

$_trajet = "Route";
$_trajet = "Time section plot";

$_niveau_de_vol = "Maximum Fligh level :";

$_N = "N";
$_S = "S";
$_E = "E";
$_O = "W";
$_symbol_degre = " ";
$_terrain = "Airfield";
$_du = "From";
$_au = "To"
$_speed_animation_obs = "Observation animation speed";
$_speed_animation_previ = "Forcast animation speed";

$_seconde ="second(s)";
$_title_hires = '<b>High resolution forecasts </b>';
$_title_hires_notice = '(instructions about fields model forecast)';
$_title_polynesie_notice = 'Legend';
$_title_imgobs_france = 'Observed imagery France';
$_title_imgobs_europe = 'Observed imagery Europe';
$_title_imgobs_polynesie = 'Observed imagery Polynesia';
$_title_zt = 'Surface analysis chart Z/T';
$_title_path = '<b>Cross-section route</b>';
$_title_path_notice = '(instructions about fields model forecast)';
$_title_vav = '<b>Dynamic aerology (predefined cross-section / relief)</b>';
$_title_vav_notice = '(instructions about fields model forecast)';
$_title_terrain = '<b>Time-section plot</b>';
$_title_terrain_notice = '(instructions about fields model forecast)';
$_title_sigmets = '<b>Sigmets </b>';
$_title_sigmets2 = '<b>Sigmets at # </b>';

$_layer_hcl = 'Boundary limit height (m)';
$_layer_vv2 = 'Vertical Speed. (m.s-1)';
$_layer_sat_ir_fr = 'Satellite IR and HRV imagery';
$_layer_sat_ir = 'Sat IR';
$_layer_sat_vis = 'Sat visible';
$_layer_radar = 'Radar imagery';
$_layer_foudre = 'Lightning';
$_layer_z = 'Geopotential height';


$_layer_hu = 'Humidity';
$_layer_iso_0 = 'Iso 0°';
$_layer_iso2_0 = 'Iso 0° (2)';
$_layer_iso_m10 = 'Iso -10°';
$_layer_iso_p5 = 'Iso +5°';
$_layer_uv_10m = 'Wind 10m';
$_layer_uv_alt = 'Upper wind';
$_layer_t = 'Temperature';
$_layer_rflctvt = 'Reflectivity';
$_layer_tke = 'TKE';
$_layer_theta = 'Theta';
$_layer_vv2 = 'Vertical Speed. (m.s-1)';
$_layer_hcl = 'Boundary limit height (m)';
$_layer_firs = 'Firs';
$_layer_airports = 'Airports';
$_layer_sigmets = 'Sigmets';

$_layer_baseLabel = 'Base maps';
$_layer_opacityLabel = 'Opacity';
$_layer_elevationLabel = 'Level';

$_layer_overlay_departement = 'Departments';
$_layer_overlay_boundary = 'Boundaries';
$_layer_overlay_graticule = 'Grids';
$_layer_overlay_airport = 'Airports';

$_loading = 'Generating';
$_error_title = 'Error !';
$_error_text = 'A error occurs, click <a href="">here</a> to retry.';
$_from = 'Date start :';
$_delay = 'Delay : ';
$_fl = 'Maximum Fligh level : ';
$_submit = 'Submit';
$_open_section = 'Open cross-section';
$_averts_sigmets = '<center><h3>AVERTISSEMENT</h3><h4>Experimental products</h4>Does not replace the consultation of SIGMET in the Messages section.<br><br>VA and TC SIGMET are not shown in this display.'
